import 'package:flutter/material.dart';

import 'package:academic_planner/src/shared/models/activity_model.dart';

final mockActivities = <ActivityModel>[
  ActivityModel(
    id: "1",
    title: "Protótipo High-Fi",
    description: "Desenvolver a interface de alta fidelidade do projeto.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Projeto",
    tags: {"Urgente", "Prática"},
    reminders: [const TimeOfDay(hour: 14, minute: 0)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "2",
    title: "Configuração de Rotas",
    description: "Implementar o sistema de rotas dinâmicas na API.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Estudo",
    tags: {"Urgente", "Teórica"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "3",
    title: "Lista de Exercícios IA",
    description: "Resolver os exercícios sobre algoritmos de busca.",
    disciplineId: 54,
    dueDate: DateTime.now().add(const Duration(days: 4)),
    category: "Estudo",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "4",
    title: "Ideia de Feature",
    description: "Esboço inicial de nova funcionalidade.",
    disciplineId: 55,
    category: "Projeto",
    tags: {},
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "5",
    title: "Revisão de Código",
    description: "Revisar pull requests pendentes.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: {"Prática"},
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "6",
    title: "Leitura de Artigo",
    description: "Ler artigo sobre arquitetura limpa.",
    disciplineId: 54,
    dueDate: DateTime.now().subtract(const Duration(days: 1)),
    category: "Leitura",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "7",
    title: "Entrega de Relatório",
    description: "Finalizar e enviar relatório final da disciplina.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(hours: 8)),
    category: "Projeto",
    tags: {"Urgente"},
    reminders: [
      const TimeOfDay(hour: 8, minute: 30),
      const TimeOfDay(hour: 12, minute: 0),
    ],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "8",
    title: "Aula Gravada Flutter",
    description: "Assistir aula sobre gerenciamento de estado.",
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 5)),
    category: "Estudo",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "9",
    title: "Refatorar Controller",
    description: "Melhorar organização e separação de responsabilidades.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: null,
    tags: {"Prática"},
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "10",
    title: "Planejamento da Semana",
    description: "Definir prioridades e organizar tarefas.",
    disciplineId: 51,
    category: "Projeto",
    tags: {"Grupo"},
    reminders: [],
    status: null,
  ),
  ActivityModel(
    id: "11",
    title: "Simulado de Prova",
    description: "Resolver prova anterior para treino.",
    disciplineId: 54,
    dueDate: DateTime.now().add(const Duration(days: 6)),
    category: "Prova",
    tags: {"Prática", "Urgente"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "12",
    title: "Atualizar Documentação",
    description: "Revisar e atualizar README do projeto.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "13",
    title: "Brainstorm de Ideias",
    description: "Levantar novas ideias para funcionalidades.",
    disciplineId: 55,
    dueDate: null,
    category: null,
    tags: {},
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "14",
    title: "Correção de Bugs",
    description: "Resolver problemas reportados no app.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: {"Urgente", "Prática", "Grupo"},
    reminders: [const TimeOfDay(hour: 9, minute: 0)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "15",
    title: "Entrega Cancelada",
    description: "Atividade cancelada pelo professor.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Estudo",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "16",
    title: "Pesquisa de Requisitos",
    description: "Entrevistar stakeholders para levantamento de dados.",
    disciplineId: 55,
    dueDate: DateTime.now().add(const Duration(days: 10)),
    category: "Projeto",
    tags: {"Grupo", "Prática"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "17",
    title: "Estudo de Caso SQL",
    description: "Analisar performance de queries complexas.",
    disciplineId: 52,
    dueDate: null,
    category: "Estudo",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "18",
    title: "Preparação para Pitch",
    description: "Montar os slides para apresentação do projeto final.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 15)),
    category: "Projeto",
    tags: {"Grupo", "Urgente"},
    reminders: [const TimeOfDay(hour: 19, minute: 30)],
    status: null,
  ),
  ActivityModel(
    id: "19",
    title: "Rascunho de Algoritmo",
    description: "Primeira versão da lógica de recomendação.",
    disciplineId: 54,
    dueDate: null,
    category: null,
    tags: {"Prática"},
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "20",
    title: "Finalizar Deploy",
    description: "Subir versão estável para o ambiente de produção.",
    disciplineId: 52,
    dueDate: DateTime.now().subtract(const Duration(hours: 2)),
    category: "Projeto",
    tags: {"Urgente"},
    reminders: [],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "21",
    title: "Seminário de Metodologias",
    description: "Apresentação em grupo sobre Kanban e XP.",
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: {"Grupo", "Teórica"},
    reminders: [const TimeOfDay(hour: 10, minute: 0)],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "22",
    title: "Resumo de Redes Neurais",
    description: "Sintetizar conceitos de Backpropagation.",
    disciplineId: 54,
    dueDate: null,
    category: "Leitura",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "23",
    title: "Configuração Firebase",
    description: "Vincular projeto Flutter ao console Firebase.",
    disciplineId: 52,
    dueDate: DateTime.now().subtract(const Duration(days: 7)),
    category: "Estudo",
    tags: {"Prática"},
    reminders: [],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "24",
    title: "Heurísticas de Nielsen",
    description: "Análise de usabilidade do app acadêmico.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 30)),
    category: "Leitura",
    tags: {"Teórica", "Importante"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "25",
    title: "Definição de Escopo",
    description: "Delimitar fronteiras do sistema de gestão.",
    disciplineId: 55,
    dueDate: DateTime.now(),
    category: "Projeto",
    tags: {"Grupo", "Prática"},
    reminders: [const TimeOfDay(hour: 20, minute: 0)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "26",
    title: "Diagrama de Classes",
    description: "Modelagem das entidades principais do domínio.",
    disciplineId: 51,
    dueDate: null,
    category: "Projeto",
    tags: {"Prática"},
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "27",
    title: "Simulado P1 Fundamentos",
    description: "Resolver questões de lógica e probabilidade.",
    disciplineId: 54,
    dueDate: DateTime.now().subtract(const Duration(days: 1)),
    category: "Prova",
    tags: {"Teórica"},
    reminders: [],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "28",
    title: "Estado com BLoC",
    description: "Refatorar gerenciamento de estado para BLoC.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 5)),
    category: "Estudo",
    tags: {"Prática", "Avançado"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "29",
    title: "Heurísticas Mobile",
    description: "Ajustar componentes para acessibilidade.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: {"Prática", "Urgente"},
    reminders: [const TimeOfDay(hour: 09, minute: 30)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "30",
    title: "Backlog do Produto",
    description: "Priorizar User Stories com o cliente.",
    disciplineId: 55,
    dueDate: DateTime.now().add(const Duration(days: 12)),
    category: "Projeto",
    tags: {"Grupo"},
    reminders: [],
    status: ActivityStatus.pending,
  ),
];
