import 'package:academic_planner/src/shared/models/activity_model.dart';

final mockActivities = <ActivityModel>[
  ActivityModel(
    id: "1",
    title: "Protótipo High-Fi",
    description: "Desenvolver a interface de alta fidelidade do projeto.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Projeto",
    tags: {"Urgente", "Prática"},
    links: [],
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "2",
    title: "Configuração de Rotas",
    description: "Implementar o sistema de rotas dinâmicas na API.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Estudo",
    tags: {"Urgente", "Teórica"},
    links: [],
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "3",
    title: "Lista de Exercícios IA",
    description: "Resolver os exercícios sobre algoritmos de busca.",
    disciplineId: 54,
    dueDate: DateTime.now().add(const Duration(days: 4)),
    category: "Estudo",
    tags: {"Teórica"},
    links: [],
    reminders: [],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "4",
    title: "Ideia de Feature",
    description: "Esboço inicial de nova funcionalidade.",
    disciplineId: 55,
    category: "Projeto",
    tags: {"Rascunho"},
    links: [],
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "5",
    title: "Revisão de Código",
    description: "Revisar pull requests pendentes.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: {"Prática"},
    links: [],
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "6",
    title: "Leitura de Artigo",
    description: "Ler artigo sobre arquitetura limpa.",
    disciplineId: 54,
    dueDate: DateTime.now().subtract(const Duration(days: 1)),
    category: "Estudo",
    tags: {"Teórica"},
    links: [],
    reminders: [],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "7",
    title: "Entrega de Relatório",
    description: "Finalizar e enviar relatório final da disciplina.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(hours: 8)),
    category: "Projeto",
    tags: {"Urgente"},
    links: [],
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "8",
    title: "Aula Gravada Flutter",
    description: "Assistir aula sobre gerenciamento de estado.",
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 5)),
    category: "Estudo",
    tags: {"Teórica"},
    links: [],
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "9",
    title: "Refatorar Controller",
    description: "Melhorar organização e separação de responsabilidades.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Projeto",
    tags: {"Prática"},
    links: [],
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "10",
    title: "Planejamento da Semana",
    description: "Definir prioridades e organizar tarefas.",
    disciplineId: 51,
    category: "Organização",
    tags: {"Rascunho"},
    links: [],
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "11",
    title: "Simulado de Prova",
    description: "Resolver prova anterior para treino.",
    disciplineId: 54,
    dueDate: DateTime.now().add(const Duration(days: 6)),
    category: "Estudo",
    tags: {"Prática"},
    links: [],
    reminders: [],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "12",
    title: "Atualizar Documentação",
    description: "Revisar e atualizar README do projeto.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: {"Teórica"},
    links: [],
    reminders: [],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "13",
    title: "Brainstorm de Ideias",
    description: "Levantar novas ideias para funcionalidades.",
    disciplineId: 55,
    category: "Projeto",
    tags: {"Rascunho"},
    links: [],
    reminders: [],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "14",
    title: "Correção de Bugs",
    description: "Resolver problemas reportados no app.",
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: {"Urgente", "Prática"},
    links: [],
    reminders: [],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "15",
    title: "Entrega Cancelada",
    description: "Atividade cancelada pelo professor.",
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Estudo",
    tags: {"Teórica"},
    links: [],
    reminders: [],
    status: ActivityStatus.canceled,
  ),
];
