import 'package:flutter/material.dart';

import 'package:academic_planner/src/shared/models/activity_model.dart';

final mockActivities = <ActivityModel>[
  ActivityModel(
    id: "1",
    title: "Protótipo High-Fi",
    description:
        '[{"insert":"Desenvolver a interface de alta fidelidade do projeto no "},{"insert":"Figma","attributes":{"bold":true}},{"insert":", focando em acessibilidade e componentes reutilizáveis.\\n\\nDeve-se seguir as diretrizes do "},{"insert":"Material Design 3","attributes":{"italic":true}},{"insert":".\\n\\nLink de referência: "},{"insert":"https://www.figma.com","attributes":{"link":"https://www.figma.com"}},{"insert":"\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 14, minute: 0)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "2",
    title: "Configuração de Rotas",
    description:
        '[{"insert":"Implementar o sistema de rotas dinâmicas na API.\\n\\n"},{"insert":"Endpoints necessários:","attributes":{"bold":true}},{"insert":"\\n"},{"insert":"GET /users","attributes":{"list":"bullet"}},{"insert":"\\n"},{"insert":"POST /auth/login","attributes":{"list":"bullet"}},{"insert":"\\n"},{"insert":"PUT /profile","attributes":{"list":"bullet"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Estudo",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "3",
    title: "Lista de Exercícios IA",
    description:
        '[{"insert":"Resolver os exercícios sobre algoritmos de busca.\\n\\n"},{"insert":"Algoritmos contemplados:","attributes":{"italic":true}},{"insert":"\\n"},{"insert":"A* (A-Estrela)"},{"insert":"\\n","attributes":{"list":"ordered"}},{"insert":"BFS (Breadth-First Search)"},{"insert":"\\n","attributes":{"list":"ordered"}},{"insert":"DFS (Depth-First Search)"},{"insert":"\\n","attributes":{"list":"ordered"}},{"insert":"\\nAs respostas devem ser enviadas via GitHub."},{"insert":"\\n"}]',
    disciplineId: 54,
    dueDate: DateTime.now().add(const Duration(days: 4)),
    category: "Estudo",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "4",
    title: "Ideia de Feature",
    description:
        '[{"insert":"Esboço inicial de nova funcionalidade para o sistema de notificações.\\n\\n"},{"insert":"Considerar o uso de Firebase Cloud Messaging.","attributes":{"bold":true,"italic":true}},{"insert":"\\nLink: "},{"insert":"https://firebase.google.com","attributes":{"link":"https://firebase.google.com"}},{"insert":"\\n"}]',
    disciplineId: 55,
    category: "Projeto",
    tags: <String>["Rascunho"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "5",
    title: "Revisão de Código",
    description:
        '[{"insert":"Revisar pull requests pendentes no repositório da equipe.\\n\\n"},{"insert":"Focar em:","attributes":{"bold":true}},{"insert":"\\n"},{"insert":"Tratamento de exceções","attributes":{"list":"bullet"}},{"insert":"\\n"},{"insert":"Nomenclatura de variáveis","attributes":{"list":"bullet"}},{"insert":"\\n"},{"insert":"Referência: "},{"insert":"https://github.com/features/code-review","attributes":{"link":"https://github.com/features/code-review"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "6",
    title: "Leitura de Artigo",
    description:
        '[{"insert":"Ler artigo sobre arquitetura limpa aplicada a sistemas reativos.\\n\\nLink do artigo oficial: "},{"insert":"https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html","attributes":{"link":"https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html"}},{"insert":"\\n"}]',
    disciplineId: 54,
    dueDate: DateTime.now().subtract(const Duration(days: 1)),
    category: "Leitura",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "7",
    title: "Entrega de Relatório",
    description:
        '[{"insert":"Finalizar e enviar relatório final pelo portal.\\n\\n"},{"insert":"Checklist de Envio:","attributes":{"bold":true}},{"insert":"\\n"},{"insert":"Introdução técnica"},{"insert":"\\n","attributes":{"list":"bullet"}},{"insert":"Metodologia aplicada"},{"insert":"\\n","attributes":{"list":"bullet"}},{"insert":"Resultados e Gráficos"},{"insert":"\\n","attributes":{"list":"bullet"}},{"insert":"\\nDocumentação em: "},{"insert":"https://docs.google.com","attributes":{"link":"https://docs.google.com"}},{"insert":"\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(hours: 8)),
    category: "Projeto",
    tags: <String>["Importante"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 8, minute: 30)],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "8",
    title: "Aula Gravada Flutter",
    description:
        '[{"insert":"Assistir aula sobre gerenciamento de estado avançado.\\n\\n"},{"insert":"Recursos Úteis:","attributes":{"italic":true}},{"insert":"\\n"},{"insert":"Documentação Flutter"},{"insert":"\\n","attributes":{"link":"https://flutter.dev","list":"bullet"}},{"insert":"Pub.dev"},{"insert":"\\n","attributes":{"link":"https://pub.dev","list":"bullet"}},{"insert":"\\n"}]',
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 5)),
    category: "Estudo",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "9",
    title: "Refatorar Controller",
    description:
        '[{"insert":"Melhorar organização seguindo os princípios "},{"insert":"SOLID","attributes":{"bold":true}},{"insert":".\\n\\nGuia de referência: "},{"insert":"https://stackoverflow.com","attributes":{"link":"https://stackoverflow.com"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "10",
    title: "Planejamento da Semana",
    description:
        '[{"insert":"Definir prioridades utilizando a metodologia "},{"insert":"Scrum","attributes":{"bold":true}},{"insert":".\\n\\n"},{"insert":"Quadro Kanban disponível em: "},{"insert":"https://trello.com","attributes":{"link":"https://trello.com"}},{"insert":"\\n"}]',
    disciplineId: 51,
    category: "Organização",
    tags: <String>["Grupo"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "11",
    title: "Simulado de Prova",
    description:
        '[{"insert":"Resolver questões na plataforma "},{"insert":"LeetCode","attributes":{"bold":true}},{"insert":" para treinar lógica.\\n\\nLink: "},{"insert":"https://leetcode.com","attributes":{"link":"https://leetcode.com"}},{"insert":"\\n"}]',
    disciplineId: 54,
    dueDate: DateTime.now().add(const Duration(days: 6)),
    category: "Prova",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "12",
    title: "Atualizar Documentação",
    description:
        '[{"insert":"Revisar o README.md e incluir instruções de "},{"insert":"Docker","attributes":{"bold":true}},{"insert":".\\n\\n"},{"insert":"Instruções:","attributes":{"italic":true}},{"insert":"\\n"},{"insert":"Instalar Docker Desktop"},{"insert":"\\n","attributes":{"list":"ordered"}},{"insert":"Rodar docker-compose up"},{"insert":"\\n","attributes":{"list":"ordered"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "13",
    title: "Brainstorm de Ideias",
    description:
        '[{"insert":"Levantar ideias no "},{"insert":"Miro","attributes":{"bold":true}},{"insert":" para o novo fluxo de checkout.\\n\\nLink: "},{"insert":"https://miro.com","attributes":{"link":"https://miro.com"}},{"insert":"\\n"}]',
    disciplineId: 55,
    category: "Projeto",
    tags: <String>["Rascunho"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "14",
    title: "Correção de Bugs",
    description:
        '[{"insert":"Verificar logs de erro no "},{"insert":"Sentry","attributes":{"bold":true}},{"insert":".\\n\\nURL do Dashboard: "},{"insert":"https://sentry.io","attributes":{"link":"https://sentry.io"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "15",
    title: "Entrega Cancelada",
    description:
        '[{"insert":"Atividade cancelada. Avisar no "},{"insert":"Slack","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Estudo",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "16",
    title: "Pesquisa de Requisitos",
    description:
        '[{"insert":"Entrevistas via "},{"insert":"Google Meet","attributes":{"bold":true}},{"insert":".\\n\\nLink da sala: "},{"insert":"https://meet.google.com","attributes":{"link":"https://meet.google.com"}},{"insert":"\\n"}]',
    disciplineId: 55,
    dueDate: DateTime.now().add(const Duration(days: 10)),
    category: "Projeto",
    tags: <String>["Grupo"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "17",
    title: "Estudo de Caso SQL",
    description:
        '[{"insert":"Otimização de queries no "},{"insert":"PostgreSQL","attributes":{"bold":true}},{"insert":".\\n\\nManual: "},{"insert":"https://www.postgresql.org","attributes":{"link":"https://www.postgresql.org"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: null,
    category: "Estudo",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "18",
    title: "Preparação para Pitch",
    description:
        '[{"insert":"Criar apresentação no "},{"insert":"Canva","attributes":{"bold":true}},{"insert":".\\n\\nLink: "},{"insert":"https://www.canva.com","attributes":{"link":"https://www.canva.com"}},{"insert":"\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 15)),
    category: "Projeto",
    tags: <String>["Grupo"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 19, minute: 30)],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "19",
    title: "Rascunho de Algoritmo",
    description:
        '[{"insert":"Pseudocódigo no "},{"insert":"Notion","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 54,
    dueDate: null,
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "20",
    title: "Finalizar Deploy",
    description:
        '[{"insert":"Configurar o "},{"insert":"GitHub Actions","attributes":{"bold":true}},{"insert":" para CD.\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().subtract(const Duration(hours: 2)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "21",
    title: "Seminário de Metodologias",
    description:
        '[{"insert":"Apresentação em grupo via "},{"insert":"Zoom","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: <String>["Grupo"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 10, minute: 0)],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "22",
    title: "Resumo de Redes",
    description:
        '[{"insert":"Ler sobre "},{"insert":"TCP/IP","attributes":{"bold":true}},{"insert":" na Wikipedia.\\n\\nLink: "},{"insert":"https://pt.wikipedia.org/wiki/TCP/IP","attributes":{"link":"https://pt.wikipedia.org/wiki/TCP/IP"}},{"insert":"\\n"}]',
    disciplineId: 54,
    dueDate: null,
    category: "Leitura",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "23",
    title: "Configuração Firebase",
    description:
        '[{"insert":"Vincular ao console oficial.\\n\\n"},{"insert":"https://console.firebase.google.com","attributes":{"link":"https://console.firebase.google.com"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().subtract(const Duration(days: 7)),
    category: "Estudo",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "24",
    title: "Heurísticas de Nielsen",
    description:
        '[{"insert":"Análise de usabilidade. Referência: "},{"insert":"https://www.nngroup.com","attributes":{"link":"https://www.nngroup.com"}},{"insert":"\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 30)),
    category: "Leitura",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "25",
    title: "Definição de Escopo",
    description:
        '[{"insert":"Documentar no "},{"insert":"Google Docs","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 55,
    dueDate: DateTime.now(),
    category: "Projeto",
    tags: <String>["Grupo"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 20, minute: 0)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "26",
    title: "Diagrama de Classes",
    description:
        '[{"insert":"Criar no "},{"insert":"Lucidchart","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 51,
    dueDate: null,
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "27",
    title: "Simulado P1",
    description:
        '[{"insert":"Questões de lógica no "},{"insert":"HackerRank","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 54,
    dueDate: DateTime.now().subtract(const Duration(days: 1)),
    category: "Prova",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.canceled,
  ),
  ActivityModel(
    id: "28",
    title: "Estado com BLoC",
    description:
        '[{"insert":"Estudar no "},{"insert":"Bloc Library","attributes":{"bold":true}},{"insert":".\\n\\nLink: "},{"insert":"https://bloclibrary.dev","attributes":{"link":"https://bloclibrary.dev"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 5)),
    category: "Estudo",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "29",
    title: "Heurísticas Mobile",
    description:
        '[{"insert":"Acessibilidade no "},{"insert":"Android Developers","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 9, minute: 30)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "30",
    title: "Backlog do Produto",
    description:
        '[{"insert":"Priorizar no "},{"insert":"Jira","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 55,
    dueDate: DateTime.now().add(const Duration(days: 12)),
    category: "Projeto",
    tags: <String>["Grupo"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "31",
    title: "Segurança de Dados",
    description:
        '[{"insert":"Criptografia com "},{"insert":"AES","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 8)),
    category: "Estudo",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "32",
    title: "Teste de Carga",
    description:
        '[{"insert":"Simular com "},{"insert":"K6","attributes":{"bold":true}},{"insert":".\\n\\nLink: "},{"insert":"https://k6.io","attributes":{"link":"https://k6.io"}},{"insert":"\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 3)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 15, minute: 0)],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "33",
    title: "Design de Ícones",
    description:
        '[{"insert":"Exportar via "},{"insert":"Adobe Express","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 53,
    category: "Projeto",
    tags: <String>["Rascunho"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "34",
    title: "Reunião de Feedback",
    description: '[{"insert":"Presencial no campus.\\n"}]',
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 2)),
    category: "Organização",
    tags: <String>[],
    reminders: <TimeOfDay>[const TimeOfDay(hour: 11, minute: 0)],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "35",
    title: "Configuração de CI/CD",
    description:
        '[{"insert":"Automatizar no "},{"insert":"GitLab","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 4)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.completed,
  ),
  ActivityModel(
    id: "36",
    title: "Estudo de UX Writing",
    description:
        '[{"insert":"Consultar guia do "},{"insert":"Medium","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 53,
    dueDate: null,
    category: "Leitura",
    tags: <String>["Teórica"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "37",
    title: "Mapeamento de Fluxo",
    description:
        '[{"insert":"Desenhar no "},{"insert":"Whimsical","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 53,
    dueDate: DateTime.now().add(const Duration(days: 5)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
  ActivityModel(
    id: "38",
    title: "Lógica de Predição",
    description:
        '[{"insert":"Script em "},{"insert":"Python","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 54,
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.draft,
  ),
  ActivityModel(
    id: "39",
    title: "Auditoria de Código",
    description:
        '[{"insert":"Análise estática com "},{"insert":"SonarQube","attributes":{"bold":true}},{"insert":".\\n"}]',
    disciplineId: 52,
    dueDate: DateTime.now().add(const Duration(days: 1)),
    category: "Projeto",
    tags: <String>["Prática"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.inProgress,
  ),
  ActivityModel(
    id: "40",
    title: "Entrega de Portfolio",
    description:
        '[{"insert":"Hospedar no "},{"insert":"Vercel","attributes":{"bold":true}},{"insert":".\\n\\nLink: "},{"insert":"https://vercel.com","attributes":{"link":"https://vercel.com"}},{"insert":"\\n"}]',
    disciplineId: 51,
    dueDate: DateTime.now().add(const Duration(days: 20)),
    category: "Projeto",
    tags: <String>["Importante"],
    reminders: <TimeOfDay>[],
    status: ActivityStatus.pending,
  ),
];
