import 'package:academic_planner/src/features/schedule/data/models/schedule_entry.dart';

enum SlotType { classTime, morningBreak, lunchBreak, afternoonBreak }

class TimeSlot {
  final String label;
  final SlotType type;

  const TimeSlot(this.label, this.type);
}

final timeSlots = <TimeSlot>[
  const TimeSlot("7:00", SlotType.classTime),
  const TimeSlot("7:50", SlotType.classTime),
  const TimeSlot("8:40", SlotType.classTime),
  const TimeSlot("INTERVALO (9:30)", SlotType.morningBreak),
  const TimeSlot("9:50", SlotType.classTime),
  const TimeSlot("10:40", SlotType.classTime),
  const TimeSlot("11:30", SlotType.classTime),
  const TimeSlot("ALMOÇO (12:20)", SlotType.lunchBreak),
  const TimeSlot("13:20", SlotType.classTime),
  const TimeSlot("14:10", SlotType.classTime),
  const TimeSlot("INTERVALO TARDE (15:00)", SlotType.afternoonBreak),
  const TimeSlot("15:20", SlotType.classTime),
  const TimeSlot("16:10", SlotType.classTime),
  const TimeSlot("17:00", SlotType.classTime),
];

final schedules = <ScheduleEntry>[
  const ScheduleEntry(disciplineId: 11, day: 2, time: "13:20", teacherId: 4),
  const ScheduleEntry(disciplineId: 11, day: 2, time: "14:10", teacherId: 4),
  const ScheduleEntry(disciplineId: 11, day: 2, time: "15:20", teacherId: 4),
  const ScheduleEntry(disciplineId: 11, day: 2, time: "16:10", teacherId: 4),
  const ScheduleEntry(disciplineId: 15, day: 3, time: "8:40", teacherId: 1),
  const ScheduleEntry(disciplineId: 15, day: 3, time: "9:50", teacherId: 1),
  const ScheduleEntry(disciplineId: 15, day: 3, time: "10:40", teacherId: 1),
  const ScheduleEntry(disciplineId: 15, day: 3, time: "11:30", teacherId: 1),
  const ScheduleEntry(disciplineId: 14, day: 4, time: "8:40", teacherId: 2),
  const ScheduleEntry(disciplineId: 14, day: 4, time: "9:50", teacherId: 2),
  const ScheduleEntry(disciplineId: 14, day: 4, time: "10:40", teacherId: 2),
  const ScheduleEntry(disciplineId: 14, day: 4, time: "11:30", teacherId: 2),
  const ScheduleEntry(disciplineId: 13, day: 4, time: "13:20", teacherId: 5),
  const ScheduleEntry(disciplineId: 13, day: 4, time: "14:10", teacherId: 5),
  const ScheduleEntry(disciplineId: 12, day: 4, time: "15:20", teacherId: 6),
  const ScheduleEntry(disciplineId: 12, day: 4, time: "16:10", teacherId: 6),
  const ScheduleEntry(disciplineId: 14, day: 5, time: "10:40", teacherId: 9),
  const ScheduleEntry(disciplineId: 14, day: 5, time: "11:30", teacherId: 9),
  const ScheduleEntry(disciplineId: 14, day: 5, time: "13:20", teacherId: 9),
  const ScheduleEntry(disciplineId: 14, day: 5, time: "14:10", teacherId: 9),
  const ScheduleEntry(disciplineId: 25, day: 1, time: "13:20", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 1, time: "14:10", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 1, time: "15:20", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 1, time: "16:10", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 2, time: "8:40", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 2, time: "9:50", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 2, time: "10:40", teacherId: 7),
  const ScheduleEntry(disciplineId: 25, day: 2, time: "11:30", teacherId: 7),
  const ScheduleEntry(disciplineId: 24, day: 3, time: "8:40", teacherId: 4),
  const ScheduleEntry(disciplineId: 24, day: 3, time: "9:50", teacherId: 4),
  const ScheduleEntry(disciplineId: 23, day: 3, time: "10:40", teacherId: 8),
  const ScheduleEntry(disciplineId: 23, day: 3, time: "11:30", teacherId: 8),
  const ScheduleEntry(disciplineId: 26, day: 4, time: "8:40", teacherId: 9),
  const ScheduleEntry(disciplineId: 26, day: 4, time: "9:50", teacherId: 9),
  const ScheduleEntry(disciplineId: 26, day: 4, time: "10:40", teacherId: 9),
  const ScheduleEntry(disciplineId: 26, day: 4, time: "11:30", teacherId: 9),
  const ScheduleEntry(disciplineId: 22, day: 4, time: "13:20", teacherId: 6),
  const ScheduleEntry(disciplineId: 22, day: 4, time: "14:10", teacherId: 6),
  const ScheduleEntry(disciplineId: 21, day: 4, time: "15:20", teacherId: 10),
  const ScheduleEntry(disciplineId: 21, day: 4, time: "16:10", teacherId: 10),
  const ScheduleEntry(disciplineId: 35, day: 2, time: "10:40", teacherId: 5),
  const ScheduleEntry(disciplineId: 35, day: 2, time: "11:30", teacherId: 5),
  const ScheduleEntry(disciplineId: 32, day: 2, time: "13:20", teacherId: 11),
  const ScheduleEntry(disciplineId: 32, day: 2, time: "14:10", teacherId: 11),
  const ScheduleEntry(disciplineId: 32, day: 2, time: "15:20", teacherId: 11),
  const ScheduleEntry(disciplineId: 32, day: 2, time: "16:10", teacherId: 11),
  const ScheduleEntry(disciplineId: 31, day: 3, time: "8:40", teacherId: 9),
  const ScheduleEntry(disciplineId: 31, day: 3, time: "9:50", teacherId: 9),
  const ScheduleEntry(disciplineId: 31, day: 3, time: "10:40", teacherId: 9),
  const ScheduleEntry(disciplineId: 31, day: 3, time: "11:30", teacherId: 9),
  const ScheduleEntry(disciplineId: 34, day: 4, time: "13:20", teacherId: 12),
  const ScheduleEntry(disciplineId: 34, day: 4, time: "14:10", teacherId: 12),
  const ScheduleEntry(disciplineId: 34, day: 4, time: "15:20", teacherId: 12),
  const ScheduleEntry(disciplineId: 34, day: 4, time: "16:10", teacherId: 12),
  const ScheduleEntry(disciplineId: 31, day: 5, time: "8:40", teacherId: 9),
  const ScheduleEntry(disciplineId: 31, day: 5, time: "9:50", teacherId: 9),
  const ScheduleEntry(disciplineId: 33, day: 5, time: "13:20", teacherId: 2),
  const ScheduleEntry(disciplineId: 33, day: 5, time: "14:10", teacherId: 2),
  const ScheduleEntry(disciplineId: 33, day: 5, time: "15:20", teacherId: 2),
  const ScheduleEntry(disciplineId: 33, day: 5, time: "16:10", teacherId: 2),
  const ScheduleEntry(disciplineId: 44, day: 2, time: "8:40", teacherId: 13),
  const ScheduleEntry(disciplineId: 44, day: 2, time: "9:50", teacherId: 13),
  const ScheduleEntry(disciplineId: 42, day: 2, time: "10:40", teacherId: 11),
  const ScheduleEntry(disciplineId: 42, day: 2, time: "11:30", teacherId: 11),
  const ScheduleEntry(disciplineId: 43, day: 2, time: "13:20", teacherId: 12),
  const ScheduleEntry(disciplineId: 43, day: 2, time: "14:10", teacherId: 12),
  const ScheduleEntry(disciplineId: 43, day: 2, time: "15:20", teacherId: 12),
  const ScheduleEntry(disciplineId: 43, day: 2, time: "16:10", teacherId: 12),
  const ScheduleEntry(disciplineId: 45, day: 4, time: "8:40", teacherId: 10),
  const ScheduleEntry(disciplineId: 45, day: 4, time: "9:50", teacherId: 10),
  const ScheduleEntry(disciplineId: 45, day: 4, time: "10:40", teacherId: 10),
  const ScheduleEntry(disciplineId: 45, day: 4, time: "11:30", teacherId: 10),
  const ScheduleEntry(disciplineId: 41, day: 4, time: "13:20", teacherId: 10),
  const ScheduleEntry(disciplineId: 41, day: 4, time: "14:10", teacherId: 10),
  const ScheduleEntry(disciplineId: 47, day: 4, time: "15:20", teacherId: 14),
  const ScheduleEntry(disciplineId: 47, day: 4, time: "16:10", teacherId: 14),
  const ScheduleEntry(disciplineId: 41, day: 5, time: "8:40", teacherId: 10),
  const ScheduleEntry(disciplineId: 41, day: 5, time: "9:50", teacherId: 10),
  const ScheduleEntry(disciplineId: 46, day: 5, time: "10:40", teacherId: 13),
  const ScheduleEntry(disciplineId: 46, day: 5, time: "11:30", teacherId: 13),
  const ScheduleEntry(disciplineId: 55, day: 1, time: "10:40", teacherId: 13),
  const ScheduleEntry(disciplineId: 55, day: 1, time: "11:30", teacherId: 13),
  const ScheduleEntry(disciplineId: 53, day: 1, time: "13:20", teacherId: 11),
  const ScheduleEntry(disciplineId: 53, day: 1, time: "14:10", teacherId: 11),
  const ScheduleEntry(disciplineId: 54, day: 1, time: "15:20", teacherId: 15),
  const ScheduleEntry(disciplineId: 54, day: 1, time: "16:10", teacherId: 15),
  const ScheduleEntry(disciplineId: 53, day: 3, time: "8:40", teacherId: 11),
  const ScheduleEntry(disciplineId: 53, day: 3, time: "9:50", teacherId: 11),
  const ScheduleEntry(disciplineId: 53, day: 3, time: "10:40", teacherId: 11),
  const ScheduleEntry(disciplineId: 53, day: 3, time: "11:30", teacherId: 11),
  const ScheduleEntry(disciplineId: 51, day: 4, time: "13:20", teacherId: 2),
  const ScheduleEntry(disciplineId: 51, day: 4, time: "14:10", teacherId: 2),
  const ScheduleEntry(disciplineId: 51, day: 4, time: "15:20", teacherId: 2),
  const ScheduleEntry(disciplineId: 51, day: 4, time: "16:10", teacherId: 2),
  const ScheduleEntry(disciplineId: 63, day: 2, time: "8:40", teacherId: 5),
  const ScheduleEntry(disciplineId: 63, day: 2, time: "9:50", teacherId: 5),
  const ScheduleEntry(disciplineId: 61, day: 2, time: "13:20", teacherId: 7),
  const ScheduleEntry(disciplineId: 61, day: 2, time: "14:10", teacherId: 7),
  const ScheduleEntry(disciplineId: 66, day: 3, time: "8:40", teacherId: 2),
  const ScheduleEntry(disciplineId: 66, day: 3, time: "9:50", teacherId: 2),
  const ScheduleEntry(disciplineId: 66, day: 3, time: "10:40", teacherId: 2),
  const ScheduleEntry(disciplineId: 66, day: 3, time: "11:30", teacherId: 2),
  const ScheduleEntry(disciplineId: 64, day: 4, time: "8:40", teacherId: 12),
  const ScheduleEntry(disciplineId: 64, day: 4, time: "9:50", teacherId: 12),
  const ScheduleEntry(disciplineId: 64, day: 4, time: "10:40", teacherId: 12),
  const ScheduleEntry(disciplineId: 64, day: 4, time: "11:30", teacherId: 12),
  const ScheduleEntry(disciplineId: 63, day: 4, time: "13:20", teacherId: 9),
  const ScheduleEntry(disciplineId: 63, day: 4, time: "14:10", teacherId: 9),
  const ScheduleEntry(disciplineId: 63, day: 4, time: "15:20", teacherId: 9),
  const ScheduleEntry(disciplineId: 63, day: 4, time: "16:10", teacherId: 9),
  const ScheduleEntry(disciplineId: 62, day: 5, time: "10:40", teacherId: 2),
  const ScheduleEntry(disciplineId: 62, day: 5, time: "11:30", teacherId: 2),
];
