import 'package:academic_planner/src/shared/models/teacher_model.dart';

const teachers = <TeacherModel>[
  TeacherModel(id: 1, name: "Marcos Vinicius Andrade Lima"),
  TeacherModel(id: 2, name: "Fernanda Costa Ribeiro"),
  TeacherModel(id: 3, name: "Rodrigo Almeida Nogueira"),
  TeacherModel(id: 4, name: "Patricia Souza Cavalcante"),
  TeacherModel(id: 5, name: "Camila Ferreira Nascimento"),
  TeacherModel(id: 6, name: "Diego Martins Carvalho"),
  TeacherModel(id: 7, name: "Juliana Pereira Rocha"),
  TeacherModel(id: 8, name: "Thiago Barbosa Correia"),
  TeacherModel(id: 9, name: "Larissa Gomes Teixeira"),
  TeacherModel(id: 10, name: "Eduardo Santos Monteiro"),
  TeacherModel(id: 11, name: "Beatriz Lima Cordeiro"),
  TeacherModel(id: 12, name: "Gustavo Henrique Vasconcelos"),
  TeacherModel(id: 13, name: "Renata Alves Fontoura"),
  TeacherModel(id: 14, name: "Vinicius Cardoso Duarte"),
  TeacherModel(id: 15, name: "Amanda Ribeiro Siqueira"),
  TeacherModel(id: 16, name: "Felipe Augusto Moreira"),
  TeacherModel(id: 17, name: "Isabela Martins Freitas"),
  TeacherModel(id: 18, name: "Rafael Nogueira Peixoto"),
  TeacherModel(id: 19, name: "Vanessa Castro Lopes"),
  TeacherModel(id: 20, name: "Bruno Cesar Andrade"),
  TeacherModel(id: 21, name: "Priscila Farias Bezerra"),
  TeacherModel(id: 22, name: "Leonardo Matos Guedes"),
  TeacherModel(id: 23, name: "Simone Araujo Vieira"),
  TeacherModel(id: 24, name: "Daniel Rocha Meireles"),
  TeacherModel(id: 25, name: "Tatiane Correia Sales"),
  TeacherModel(id: 26, name: "Marcelo Dantas Coelho"),
  TeacherModel(id: 27, name: "Aline Sousa Barreto"),
  TeacherModel(id: 28, name: "Igor Pimentel Cavalcanti"),
  TeacherModel(id: 29, name: "Cristina Melo Andrade"),
  TeacherModel(id: 30, name: "Fabio Henrique Lacerda"),
  TeacherModel(id: 31, name: "Eduardo Santos Monteiro"),
  TeacherModel(id: 32, name: "Michele Torres Aguiar"),
  TeacherModel(id: 33, name: "Alexandre Nunes Pontes"),
  TeacherModel(id: 34, name: "Sabrina Diniz Marques"),
  TeacherModel(id: 35, name: "Leonardo Matos Guedes"),
  TeacherModel(id: 36, name: "Wesley Batista Fagundes"),
  TeacherModel(id: 37, name: "Carla Regina Amaral"),
  TeacherModel(id: 38, name: "Ricardo Bastos Feitosa"),
  TeacherModel(id: 39, name: "Valnyr Vasconcelos Lira"),
];
